SENDGRID_API_KEY = "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"
GEMINI_API_KEY = "AIzaSyDov0k-eA9ZR1E6TIIiHD2SLf6mShpB8NI"
GROQ_API_KEY = "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"

DB_HOST = "ep-broad-bush-a5xjz0wm-pooler.us-east-2.aws.neon.tech"
DB_NAME = "neondb"
DB_USER = "neondb_owner"
DB_PASSWORD = "npg_LgZ4en1QpsyD"
DB_PORT = "5432"

